### ISSUE TITLE
Comparison to pytorch-lightning?

### ISSUE THREAD

**Issue by mpariente** [davidalvarezdlt/skeltorch#1]
Hi David, 

Thank you very much for your work. 
I didn't go through all the tutorials and the docs (looks nicely organized by the way). I just wanted to ask if you could tell which features here are not in pytorch-lightning already? What are the main design differences? 

Thanks,

**Comment by davidalvarezdlt** [comment]
Hi Manuel, thank you for your question.

If I'm honest, I didn't know about the existence of `pytorch-lightning` (my fault). I've been reading the docs they provide and I've found several similarities and a few differences:

+ Both provide an interface to avoid boilerplate code.
+ Both provide hooks to modify the default behavior of the pipelines, which is fundamental.

With respect to the differences:

- Skeltorch forces you to structure your project in a certain way, which should be equal in all Skeltorch projects. For me, that was one of the most important points when designing it, as it's easier for other people to find pieces of code that they may be interested in.
- Skeltorch provides an easy interface to share experiments with others. Every time you create a new experiment with the `init` pipeline, a new experiment is created inside your experiments folder. To share that project, the only thing you need is to zip it and share it. That experiment folder contains not only checkpoints, but also information about how the data has been treated, log information or configuration details. 
- Skeltorch already comes with an implemented textual logger ('logging.Logger') and a TensorBoard logger. No boilerplate code on that point. I'm seeing that in pytorch-lightning you have to deal with it.
- **Automatic restoration** of both checkpoints and random seeds in Skeltorch (not sure whether pytorch-lightning provides it). 

I could mention more differences, but I prefer to summarize them in one main difference: Skeltorch wants to create a unified standard to create and share PyTorch projects by automatic as many tasks as possible; pytorch-lightning wants to increase productivity but provides an open interface so developers do it the way they prefer, so they can't automatize as many things as we do.

**Comment by mpariente** [comment]
Thanks for you answer !

* > Skeltorch forces you to structure your project in a certain way, which should be equal in all Skeltorch projects. For me, that was one of the most important points when designing it, as it's easier for other people to find pieces of code that they may be interested in.
> 
I do understand that point. It will be very valuable when `skeltorch` will be more largely adopted.

* >    Skeltorch provides an easy interface to share experiments with others. Every time you create a new experiment with the `init` pipeline, a new experiment is created inside your experiments folder. To share that project, the only thing you need is to zip it and share it. That experiment folder contains not only checkpoints, but also information about how the data has been treated, log information or configuration details.

* > Skeltorch already comes with an implemented textual logger ('logging.Logger') and a TensorBoard logger. No boilerplate code on that point. I'm seeing that in pytorch-lightning you have to deal with it.
> 
Actually, it is the same in pytorch-lightning, TensorBoard is the default logger, but others are also supported.

* >  **Automatic restoration** of both checkpoints and random seeds in Skeltorch (not sure whether pytorch-lightning provides it).
> 
I don't know about random seeds and that's a very good point actually, but checkpoints can be restored automatically. 
> 
* > I could mention more differences, but I prefer to summarize them in one main difference: Skeltorch wants to create a unified standard to create and share PyTorch projects by automatic as many tasks as possible; pytorch-lightning wants to increase productivity but provides an open interface so developers do it the way they prefer, so they can't automatize as many things as we do.
> 

You might be interested by [this subproject](https://github.com/PyTorchLightning/pytorch-lightning-conference-seed) of `pytorch-lightning`

**Comment by davidalvarezdlt** [comment]
Thank you so much for your feedback. In the end, I think that having both options is great for the community. There aren't lucrative intentions behind any of the projects, and so the better they become (maybe learning from each other), the better for the community.

If you finally try `Skeltorch` and you find ways to improve it, I encourage you to be part of the project by contributing yourself.
